{% set version = "3.3.90.3" %}

package:
  name: eigen4rkt
  version: {{ version }}

source:
  url: https://github.com/reaktoro/eigen4rkt/archive/v{{ version }}.tar.gz
  sha256: 38b009a0ccbdf745b12929cc734323e47848957ed4f04a86402df7351fef8f51

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  run_constrained:
    - eigen ==999999999999  # To avoid conflicts, eigen4rkt and eigen cannot coexist in the same conda environment.
test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
  files:
    - test/
  commands:
    - test -d ${PREFIX}/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1  # [win]

about:
  home: https://github.com/reaktoro/eigen4rkt
  license: MPL-2.0
  license_family: MOZILLA
  license_file: COPYING.MPL2
  summary: eigen4rkt is a fork of eigen to be used in Reaktoro (it exists solely to produce conda-forge package with most up-to-date version of eigen, not yet released by the eigen team)
  doc_url: https://github.com/reaktoro/eigen4rkt
  dev_url: https://github.com/reaktoro/eigen4rkt

extra:
  recipe-maintainers:
    - allanleal
